### ISSUE TITLE
Failing coverage check on forked Pull Requests

### ISSUE THREAD

**Issue by dopecodez** [dopecodez/Wikipedia#18]
As seen on #17 , #12 , #11 and any other forked PRs to master, the coverage check fails.

The check fails due to `CC_TEST_REPORTER_ID` which is used in uploading test reports to [codeclimate](https://codeclimate.com/) not being available to forks. The discussion at https://github.community/t/make-secrets-available-to-builds-of-forks/16166 is inconclusive, meaning we have to find our own solution or remove the check completely.

Possible solutions include:

1. Find a way to make `CC_TEST_REPORTER_ID` available to forks following the above link.
2. Remove the check from PRs. This will involve playing around with the [main.yaml](https://github.com/dopecodez/Wikipedia/blob/master/.github/workflows/main.yml) github action file to get it just right.
3. **Non Ideal** Make `CC_TEST_REPORTER_ID` public. This is something we really shouldnt do as people using parts of the code might end up using this secret.

**Comment by friendofdog** [comment]
I'm not so familiar with CI on Github, but if `CC_TEST_REPORTER_ID` was made available to forks isn't that the same as making it public? For example, I could just do something like `echo $CC_TEST_REPORTER_ID` and I'd have the key.

**Comment by dopecodez** [comment]
I just made a commit to master which should solve this case by using [if](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions) in the `.github` ci file. We'll need to test if this works on the next fork before closing this.

**Comment by dopecodez** [comment]
Thanks for the help everyone, it was fixed by having another look at github actions conditionals.
