### ISSUE TITLE
Won't load in a secure context (https)

### ISSUE THREAD

**Issue by marcellobarile** [dopecodez/Wikipedia#26]
Mixed Content: The page at '{APP_DOMAIN}' was loaded over HTTPS, but requested an insecure resource 'http://en.wikipedia.org/w/api.php?list=search&srprop=&srlimit=10&srsearch={QUERY}&format=json&redirects=&action=query&origin=*&'. This request has been blocked; the content must be served over HTTPS.

**Comment by dopecodez** [comment]
Ah, thanks for pointing that out.

In (request.ts)[https://github.com/dopecodez/Wikipedia/blob/master/source/request.ts#L4], we are using `http` and not `https`. This should ideally be in a secure context.

Simple fix, will require some manual testing to make sure the routes work with `https`.
