### ISSUE TITLE
Use encodeUriComponent() instead of encodeURI() for better encoding for search params

### ISSUE THREAD

**Issue by harisangarans** [dopecodez/Wikipedia#31]
I like to change to encodeUriComponent() instead of encodeURI() for better encoding for search params.

**Comment by dopecodez** [comment]
Sounds like a good option. `encodeUriComponent` is the safer option for us to use.

A good PR would be welcome for this.

**Comment by dopecodez** [comment]
Closing this issue as this is handled better with `encodeURI()`
