### ISSUE TITLE
Stray console.log

### ISSUE THREAD

**Issue by leemm** [dopecodez/Wikipedia#36]
Hi, 

It's possible to remove this [https://github.com/dopecodez/Wikipedia/blob/master/source/request.ts#L50](https://github.com/dopecodez/Wikipedia/blob/master/source/request.ts#L50) which is causing problems with the console in my app?
I can PR if that's the preference.

Thanks!

**Comment by dopecodez** [comment]
Good catch, definitely a stray console log we missed. You can raise a PR if you want to or I'll put up a fix for this in a couple of days. Thanks for reporting!

**Comment by dopecodez** [comment]
Closed #36

**Comment by leemm** [comment]
Oh thanks for fixing. I forgot to put in a PR :D 👍
