### ISSUE TITLE
Implement random page API

### ISSUE THREAD

**Issue by dopecodez** [dopecodez/Wikipedia#4]
There are a lot of new REST APIs for wikipedia present in the REST API docs.

We'll look through them one by one and implement the same. Any one who wants to pick up on any other REST API should ideally open a new issue.

The REST API has a [/page​/random​/{format}](https://en.wikipedia.org/api/rest_v1/#/Page%20content/get_page_random__format_
) endpoint which which gives a page in given format. This is something I would love to have in wikipedia. Find more details [here](https://en.wikipedia.org/api/rest_v1/#/Page%20content/get_page_random__format_
).

Implementation for this should follow the summary or related method flow. Remember to write unit tests for all possible scenarios in your new functions, and try to use types as far as possible.

I'll be happy to help anyone who wants to pick this up.

**Comment by friendofdog** [comment]
Are you still looking for help on this issue? If so, I'd like to pitch in.

I'm not sure what is meant by, "Implementation for this should follow the summary or related method flow". But I'm fine writing tests and using types.

**Comment by dopecodez** [comment]
Sure, @friendofdog , help with this would be welcome.

You only need to use types and write unit tests, you can ignore the other part

**Comment by friendofdog** [comment]
Understood, @dopecodez . I wrote tests and a basic implementation. (Pardon me for doing so, I borrowed much from existing tests. First time using Jest.)

As for types, the Wikipedia.org API returns six unique types: 5 kinds of JSON objects or an HTML string. Should I add the missing types to `resultTypes.js` or is this a bit overkill?

**Comment by dopecodez** [comment]
I think it's best to borrow from existing tests. 

That's an interesting question, I think we can skip over the types not currently present in the package. We would ideally need to implement the method like `mobile-sections` and the rest before we support the same in random.

I will take a detailed look at your changes once you open an MR, @friendofdog , thanks.

**Comment by friendofdog** [comment]
Pardon the delay.

I took a look at the return formats from the API and they all looked fairly essential. So I just went ahead and creates types for all of them.

Just made a draft PR, #11. How does it look?

**Comment by dopecodez** [comment]
Looks good, @friendofdog . Lets continue this conversation there.
