### ISSUE TITLE
Dropping support for node 10, 12

### ISSUE THREAD

**Issue by dopecodez** [dopecodez/Wikipedia#41]
We are planning to drop support for node versions:

10.x.x
12.x.x
Our minimum version will be node 14.x.x.

It would be great to hear if the community feels like there might be an issue to dropping these versions.

**Comment by recleun** [comment]
What's the benefit of dropping support for versions older than 14.x.x?

**Comment by dopecodez** [comment]
There a few reasons why open source packages should support the newer versions.

1.  The official node team currently supports node 14 as the lowest version. Supporting versions lower than this can cause issues with node in the future as the lower versions are deprecated. You can check out https://github.com/nodejs/Release#readme to see the node versions currently under  support and maintanance.
2. When coding using the newest node features can use packages and newest coding standards. It will really help maintaining the package in the long run.
cc: @recleun

**Comment by recleun** [comment]
> There a few reasons why open source packages should support the newer versions.

After reading your reply, I do agree with dropping support, since there is no reason for anyone to use an out of support version of node.

**Comment by dopecodez** [comment]
changes done with #44
