### ISSUE TITLE
Move from node-fetch to got,ky or axios

### ISSUE THREAD

**Issue by dopecodez** [dopecodez/Wikipedia#45]
### Issue

Updating node-fetch is a headache because the module seems to be using different formats which are not supported by modern `typescript` compilers and `jest`, both libraries which are very widely used. Additionally, node-fetch takes up a few more mbs as shown in https://www.npmjs.com/package/got#comparison, and also is less actively maintained.

### Solution

Analyze the other major HTTP modules like got, ky, or Axios and transition Wikipedia to these libraries instead of node-fetch.
My initial feeling is using got because of its small size and active maintenance but other suggestions are welcome.

**Comment by gtibrett** [comment]
Submitted https://github.com/dopecodez/Wikipedia/pull/47

**Comment by dopecodez** [comment]
Closed via #47
